### ISSUE TITLE
Cant build servise fleet manager

### ISSUE THREAD

**Issue by RuslanShmateyev** [ALLTERCO/fleet-management#8]
Install Node js (v12.22.9) and npm (v8.5.1), use commands from [docs](https://github.com/ALLTERCO/fleet-management/blob/main/docs/developing.md):
```
cd ./frontend
npm run install
npm run build
cd ../backend
npm install
npm run build
npm start
```
Command `npm run install` isnt declared in package.json in frontend folder and when i use it, i got error:
```
npm ERR! Missing script: "install"
npm ERR!
npm ERR! Did you mean this?
npm ERR!     npm uninstall # Remove a package
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-04-13T19_52_24_138Z-debug-0.log
```
I use `npm install`.
But when i run `npm run build` it gives me error:
```
**file:///home/fleet-management-main/frontend/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)**
```
In backend `npm install` and `npm run build` worked, but also didnt work command `npm start` and throws error:
```
/home/fleet-management-main/backend/dist/DeviceManager.js:113
    if (typeof req?.method === 'string' && res.result != undefined) {
                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/fleet-management-main/backend/dist/app.js:45:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
OS system: Linux Ubuntu 22.04.4 LTS

**Comment by ComBoro** [comment]
Hi @RuslanShmateyev, can you try using a newer version of node, preferably the LTS version (currently v20.12.2)
